# Generated by Django 3.1.1 on 2020-10-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201018_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='approved_comment',
        ),
    ]
